name: Proselint with Spell Check

on:
  push:
    paths:
      - '**/*.md'
  pull_request:
    paths:
      - '**/*.md'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install proselint
        run: pip install proselint

      - name: Lint all .md files with proselint
        run: find . -name '*.md' -exec proselint {} \;

      - name: Check spelling with misspell
        uses: reviewdog/action-misspell@v1
        with:
          locale: "US"

